Update trytravis.py
SethMichaelLarson/trytravis pull request #22
Opened 2017-09-01 12:01 UTC by miguelbalparda

This PR should give trytravis the option to just submit the tests to Travis and don't wait until they are done.
Fixes #17

2017-09-01 13:49 UTC, sethmlarson requested changes
Thanks for submitting this! I have one comment. Also could we also have a CHANGELOG entry under `Added`?

2017-09-01 13:49 UTC, SethMichaelLarson commented on trytravis.py
> +            commit, committed = _submit_changes_to_github_repo(os.getcwd(), url)
This line is a little too long and is tripping our linter.

2017-09-01 14:06 UTC, SethMichaelLarson commented
Might want to change your `trytravis` target repo from your fork to a different GitHub repository. :)

2017-09-01 14:11 UTC, miguelbalparda commented
I was actually trying to run trytravis for my fork to stop all the unnecesary noise here, sorry about that.

2017-09-05 16:16 UTC, miguelbalparda commented
How do you want to handle the CHANGELOG entry? Should I add it under the current version? What about the codecov fails?

2017-09-05 16:59 UTC, SethMichaelLarson commented
You can add it under a new version labeled "Unreleased" or under the next incremented minor. Don't worry about the codecov fails.

2017-09-12 17:51 UTC, miguelbalparda commented
Sorry for the late reply, just added this to the README.md

2017-09-12 17:54 UTC, SethMichaelLarson commented
Thanks! This is looking good :)

2017-09-13 01:03 UTC, merged